import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    minify: prod,
    minifyIdentifiers: prod,
    minifySyntax: prod,
    minifyWhitespace: prod,
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    splitting: false,
    metafile: prod,
    pure: ['console.debug'],
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins],
    format: 'cjs',
    target: 'es2018',
    logLevel: "info",
    define: prod ? {
        'process.env.NODE_ENV': '"production"',
        'process.env.DEBUG': 'false'
    } : {
        'process.env.NODE_ENV': '"development"',
        'process.env.DEBUG': 'true'
    },
    outfile: 'main.js',
    plugins: [
        {
            name: 'bundle-analyzer',
            setup(build) {
                build.onEnd((result) => {
                    if (prod && result.metafile) {
                        console.log('\n📊 Bundle Analysis:');
                        const outputs = result.metafile.outputs;
                        for (const [file, output] of Object.entries(outputs)) {
                            if (file.endsWith('.js')) {
                                const sizeKB = (output.bytes / 1024).toFixed(2);
                                console.log(`  ${file}: ${sizeKB} KB`);
                            }
                        }

                        console.log('\n📦 Largest Imports:');
                        const inputs = result.metafile.inputs;
                        const imports = Object.entries(inputs)
                            .sort(([,a], [,b]) => (b.bytes || 0) - (a.bytes || 0))
                            .slice(0, 10);

                        imports.forEach(([file, input]) => {
                            const sizeKB = (input.bytes / 1024).toFixed(2);
                            console.log(`  ${file}: ${sizeKB} KB`);
                        });
                    }
                });
            }
        }
    ]
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}