/**
 * Advanced Template Service
 * Jinja-style templating for note generation
 */

export interface TemplateVariables {
    title: string;
    author: string;
    url: string;
    videoId: string;
    transcript: string;
    summary: string;
    timestamp: string;
    tags?: string[];
    duration?: string;
    publishedAt?: string;
    [key: string]: any;
}

export interface Template {
    id: string;
    name: string;
    description: string;
    content: string;
    variables: string[];
}

export class TemplateService {
    private templates: Map<string, Template> = new Map();

    constructor() {
        this.registerDefaultTemplates();
    }

    private registerDefaultTemplates(): void {
        this.templates.set('executive', {
            id: 'executive',
            name: 'Executive Summary',
            description: 'Brief executive summary (≤250 words)',
            content: `# {{title}}

**Author**: {{author}}
**Video**: [Watch on YouTube]({{url}}
**Date**: {{timestamp}}

## Summary

{{summary}}

## Tags
{% if tags %}{% for tag in tags %}#{{tag}} {% endfor %}{% endif %}`,
            variables: ['title', 'author', 'url', 'timestamp', 'summary', 'tags'],
        });

        this.templates.set('detailed', {
            id: 'detailed',
            name: 'Detailed Guide',
            description: 'Comprehensive detailed guide',
            content: `# {{title}}

> By {{author}}

## Video Information
- **URL**: {{url}}
- **Duration**: {{duration}}
- **Published**: {{publishedAt}}

## Summary

{{summary}}

## Key Points

{{transcript}}

---
*Generated by YouTube Clipper on {{timestamp}}*`,
            variables: ['title', 'author', 'url', 'duration', 'publishedAt', 'summary', 'transcript', 'timestamp'],
        });

        this.templates.set('brief', {
            id: 'brief',
            name: 'Brief Overview',
            description: 'Quick overview (≤100 words)',
            content: `# {{title}}

{{summary}}

[Source]({{url}}) | {{author}} | {{timestamp}}`,
            variables: ['title', 'summary', 'url', 'author', 'timestamp'],
        });

        this.templates.set('code-tutorial', {
            id: 'code-tutorial',
            name: 'Code Tutorial',
            description: 'For programming tutorials',
            content: `# {{title}} - Code Tutorial

**Author**: {{author}}

## Summary

{{summary}}

## Code Snippets

{% for code in codeSnippets %}
\`\`\`{{code.language}}
{{code.content}}
\`\`\`
{% endfor %}

## Transcript

{{transcript}}`,
            variables: ['title', 'author', 'summary', 'codeSnippets', 'transcript'],
        });
    }

    render(templateId: string, variables: TemplateVariables): string {
        const template = this.templates.get(templateId);
        if (!template) {
            throw new Error(`Template '${templateId}' not found`);
        }

        return this.renderTemplate(template.content, variables);
    }

    private renderTemplate(content: string, variables: TemplateVariables): string {
        let result = content;

        // Simple variable substitution {{variable}}
        result = result.replace(/\{\{(\w+)\}\}/g, (_, key) => {
            return variables[key] || '';
        });

        // Conditionals {% if variable %}...{% endif %}
        result = result.replace(/\{%\s*if\s+(\w+)\s*%\}([\s\S]*?)\{%\s*endif\s*%\}/g, (_, condition, body) => {
            const value = variables[condition];
            return value ? body : '';
        });

        // Loops {% for item in items %}...{% endfor %}
        result = result.replace(/\{%\s*for\s+(\w+)\s+in\s+(\w+)\s*%\}([\s\S]*?)\{%\s*endfor\s*%\}/g, (_, itemName, arrayName, body) => {
            const array = variables[arrayName];
            if (!Array.isArray(array)) return '';

            return array.map(item => {
                let itemBody = body;
                if (typeof item === 'object' && item !== null) {
                    Object.keys(item).forEach(key => {
                        itemBody = itemBody.replace(new RegExp(`{{${itemName}\\.${key}}}`, 'g'), item[key]);
                    });
                }
                return itemBody;
            }).join('');
        });

        return result;
    }

    registerTemplate(template: Template): void {
        this.templates.set(template.id, template);
    }

    getTemplate(id: string): Template | undefined {
        return this.templates.get(id);
    }

    getAllTemplates(): Template[] {
        return Array.from(this.templates.values());
    }

    deleteTemplate(id: string): boolean {
        return this.templates.delete(id);
    }
}

export const templateService = new TemplateService();
