#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged to format and lint changed files
npx lint-staged

# Run type checking
npm run type-check

# Run tests on affected files
npx jest --passWithNoTests --bail
